# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boot_stat <- function(mat, boot_indices, method) {
    .Call(`_riboTransVis_boot_stat`, mat, boot_indices, method)
}

rolling_window_sum <- function(positions, expressions, window, type) {
    .Call(`_riboTransVis_rolling_window_sum`, positions, expressions, window, type)
}

